In [5]:
import sys
import os

root = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(root)

In [14]:
from models.LinearRegression import LinearRegression
from training.train import train_regression
from training.evaluate import evaluate

In [35]:
from sklearn.datasets import make_regression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
import numpy as np

X, y = make_regression(n_samples = 1000, n_features = 3, noise = 3, random_state = 42)
y = np.expand_dims(y, -1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

print(X[:3, :], "\n", y[:3])

model = LinearRegression()
model = train_regression(model, X_train, y_train)

evaluate(model, mean_squared_error, X_test, y_test)

[[-0.18912039 -1.33031363  0.92165011]
 [-0.65332923 -0.47494531  1.76545424]
 [-0.22485598  0.07685188 -0.65000258]] 
 [[-101.36560262]
 [ -58.19709597]
 [ -31.34992158]]


9.294530496557904